site_name: MkDocs Template
site_description: MkDocs Template
repo_url: https://github.com/FabLabReykjavik/MkDocsGitHubPagesTemplate
edit_uri: edit/main/docs/
repo_name: "Github"

theme:
  name: material
  logo: 
  #favicon: assets/logo/favicon/favicon.png
  language: en


  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.expand

  palette:
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey 
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

#extra_css:
#  - stylesheets/extra.css

plugins:
#  - social
  - search
# - tags
# - tags:
#      tags_file: tags.md

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg



